name: Docker Build Action

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: [self-hosted, docker]
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Ros Node in the Docker image
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:${{ github.sha }}
